### ISSUE TITLE
[bug-website module] [ManhuaES]

### ISSUE THREAD

**Issue by SoulSlashMaster** [dazedcat19/FMD2#180]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 Pro 64 bit

**Describe the bug**
It seems to be downloading the covers from the bottom of the page. Seems to happen with every chapter.
**Expected behavior**
Should only be getting the images from the chapter.

**Screenshots**
https://manhuaes.com/chapter/wan-gu-shen-wang-chapter-161/
![image](https://user-images.githubusercontent.com/42787140/100105772-58041280-2e2d-11eb-9270-a94b1fdb6a37.png)

**Comment by SoulSlashMaster** [comment]
Yeah fixed that chapter but now broke other chapters with it. example: https://manhuaes.com/chapter/sky-sword-god-chapter-76/
I got the old lua for it and it worked but not on the new updated lua. Guess it breaks older chapters.
The log just says download failed.
[fmd.log](https://github.com/dazedcat19/FMD2/files/5593719/fmd.log)

**Comment by Slasar41** [comment]
Should be fixed.
Please test if there still has issue with other chapters.

**Comment by SoulSlashMaster** [comment]
Thanks fixed most of the chapters from before.
Here are some chapters that are still broken and can't be downloaded.
 
https://manhuaes.com/chapter/sky-sword-god-chapter-30/
https://manhuaes.com/chapter/sky-sword-god-chapter-100/
https://manhuaes.com/chapter/wan-gu-shen-wang-chapter-186/
https://manhuaes.com/chapter/wan-gu-shen-wang-chapter-206/
More chapters in the log. You can ignore the ones that say no cloudflare since the chapters are broken on the website for them.
[fmd.log](https://github.com/dazedcat19/FMD2/files/5597058/fmd.log)

**Comment by Slasar41** [comment]
Should be fixed.
Let me know if there are some chapters that still can't be downloaded.
