### ISSUE TITLE
Stuck at update dialog

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#2]
There's a new update for the website modules and FMD simultaneously.
If I press `Yes` at the modules dialog update and enable the `Auto restart` option, then FMD will trying to restart after finish download the modules.
![image](https://user-images.githubusercontent.com/28888646/82489002-1ce5f700-9b0b-11ea-8eaf-31028bd348e1.png)
But the FMD dialog update still open and will hold the process to restart.
![image](https://user-images.githubusercontent.com/28888646/82489011-1fe0e780-9b0b-11ea-96de-410322b0db9c.png)

**Comment by dazedcat19** [comment]
I thought I already fixed this issue. There's a commit about registering extra form to close.
https://github.com/dazedcat19/FMD2/blob/master/mangadownloader/forms/uBaseForms.pas

**Comment by Slasar41** [comment]
Well it's still happen to me.
Is it already implemented in version 2.0.3.0?

**Comment by dazedcat19** [comment]
yes. the closemodal must be only fired from mainthred. the clear method called in restartfmd. restartfmd already in synchronize event. so it should be ok. I'll check it later.
